Tienda/urls.py
from django.contrib import admin
from django.urls import path
from .views import *

app_name = 'Tienda'
urlpatterns = [
    path('', index, name="Index"),
    path('new_product/', newProduct, name="NewProduct"),
    path('new_category/', newCategory, name="NewCategory"),
    path('cart/', listCart, name="Cart"),
    path('cart/clean', cleanCart, name="CleanCart"),
    path('addCart/<int:idProduct>', addCart, name="AddCart"),
    path('cart/deduct/<int:idProduct>', deductCart, name="DeductCart"),
    path('cart/sale', sale, name="Sale"),
    path('registration/', register, name="Register"),
    path('logout/', logout, name="Logout"),

    
]

core/urls.py
from django.contrib import admin
from django.urls import path, include
from Tienda import views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    #path('', views.index),
    path('', include('Tienda.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
]
urlpatterns+=static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

templates/base.html
<!DOCTYPE html>
<html lang="en">
    <head>
        {% load static %}
        <meta charset="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
        <meta name="description" content="" />
        <meta name="author" content="" />
        <title>{% block title %}{% endblock title %}</title>
        <!-- Favicon-->
        <link rel="icon" type="image/x-icon" href="{% static 'assets/tienda.png' %}" />
        <!-- Bootstrap icons-->
        <link href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.5.0/font/bootstrap-icons.css" rel="stylesheet" />
        <!-- Core theme CSS (includes Bootstrap)-->
        <link href="{% static 'css/styles.css' %}" rel="stylesheet" />
    </head>
    <body>

        <!-- Navigation-->
        <nav class="navbar navbar-expand-lg navbar-light bg-light">
            <div class="container px-4 px-lg-5">
                <a class="navbar-brand" href="{% url 'Tienda:Index' %}">MyShop</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation"><span class="navbar-toggler-icon"></span></button>
                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <ul class="navbar-nav me-auto mb-2 mb-lg-0 ms-lg-4">
                        <li class="nav-item"><a class="nav-link active" aria-current="page" href="{% url 'Tienda:Index' %}">Home</a></li>
                        <li class="nav-item"><a class="nav-link" href="#!">About</a></li>
                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle" id="navbarDropdown" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">Shop</a>
                            <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                                <li><a class="dropdown-item" href="#!">All Products</a></li>
                                <li><hr class="dropdown-divider" /></li>
                                <li><a class="dropdown-item" href="#!">Popular Items</a></li>
                                <li><a class="dropdown-item" href="#!">New Arrivals</a></li>
                            </ul>
                        </li>
                        <!--  New dropdown    -->
                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle" id="navbarDropdown" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">Manage</a>
                            <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                                <li><a class="dropdown-item" href="{% url 'Tienda:NewProduct' %}">New Products</a></li>
                                <li><a class="dropdown-item" href="{% url 'Tienda:NewCategory' %}">New Categories</a></li>
                                <li><a class="dropdown-item" href="/admin">Admin</a></li>
                            </ul>
                        </li>
                        <!-- Fin New dropdown    -->
                    </ul>
                    <form id="searchForm" class="form-check-inline" action="" method="POST"> {% csrf_token %}
                        <input type="text" name="search" placeholder="search...">
                        
            
                        <a href="{% url 'Tienda:Cart' %}">
                        <button type="submit" class="btn btn-outline-dark">
                            <i class="bi bi-search"></i>
                        </button>
                        </a>
                    </form>
                    
                    {% if request.user.is_authenticated %}
                    <span class="mx-2"> Hi {{user.username}} </span>
                    <a class="mx-2" href="{% url 'Tienda:Cart' %}">
                        <button class="btn btn-outline-dark" type="submit">
                            <i class="bi-cart-fill me-1"></i>
                            Cart
                            <span id="spanCart" class="badge bg-dark text-white ms-1 rounded-pill">0</span>
                        </button>
                        </a>
                    <a href="{% url 'logout' %}">Logout</a>
            
            

                    {% else %}


        
                        <a class="mx-2" href="{% url 'login' %}">Login</a> 
                        <a class="mx-1" href="{% url 'Tienda:Register' %}">Register</a> 
                            
                    
                    {% endif%}



                        
                    
                </div>
            </div>
        </nav>        


        <!-- Header-->
        <header class="bg-dark py-5">
            <div class="container px-4 px-lg-5 my-5">
                <div class="text-center text-white">
                    <h1 class="display-4 fw-bolder">MyShop</h1>
                    <p class="lead fw-normal text-white-50 mb-0"></p>
                </div>
            </div>
        </header>

        {% block content %}{% endblock content %}       

        
        <!-- Footer-->
        <footer class="py-5 bg-dark">
            <div class="container"><p class="m-0 text-center text-white">Copyright &copy; José Angel Rojas Valerio</p></div>
        </footer>
        <!-- Bootstrap core JS-->
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"></script>
        <!-- Core theme JS-->
        <script src="{% static 'js/scripts.js' %}"></script>
    </body>
</html>

templates/cart.html
{% extends 'base.html' %}
{% load static %}
{% block title %}Shop - Cart{% endblock title %}


{% block content %}

<h1>Shopping Cart</h1>

<table class="table">
<tr>
    <th>Product</th>
    <th>Quantity</th>
    <th>Price</th>
    <th>Deduct</th>
</tr>

{% for id, value in cart.items %}
     <tr>
     <td>{{ value.code }}</td>
     <td>{{ value.title }}</td>
     <td>{{ value.quantity }}</td>
     <td>${{ value.price }}</td>
     <td><a href="{% url 'Tienda:DeductCart' value.product_id %}">X</a></td>
     </tr>    
    
{% endfor %}

</table>

<a href="{% url 'Tienda:CleanCart' %}">Clean Cart</a>
<span>{{total_cart}}</span>

<form method="post" action="sale">
  {% csrf_token %}

    <input type="submit" value="Close sale" />

  </form>

<script>
    window.onload = function () {
      setCart({{ lenCart }})
    }
  </script>
{% endblock content %}

templates/index.html
{% extends 'base.html' %}
{% load l10n %}
{% block title %}Shop - Home{% endblock title %}

<!-- imagen random ->  <img class="card-img-top" src="https://dummyimage.com/450x300/dee2e6/6c757d.jpg" alt="..." /> -->

{% block content %}

    <!-- Section-->
    <section class="py-5">
        <div class="container px-4 px-lg-5 mt-5">
            <div class="row gx-4 gx-lg-5 row-cols-2 row-cols-md-3 row-cols-xl-4 justify-content-center">

                {% for product in products %}
                <div class="col mb-5">
                    <div class="card h-100">
                        <!-- Product image-->
                        <img class="card-img-top" src="{{product.image.url}}" alt="{{product.title}}" />
                        <!-- Product details-->
                        <div class="card-body p-4">
                            <div class="text-center">
                                <!-- Product name-->
                                <h5 class="fw-bolder">{{product.title}}</h5>
                                <!-- Product price-->
                                {{product.price|unlocalize}}
                            </div>
                        </div>
                        <!-- Product actions-->
                        <div class="card-footer p-4 pt-0 border-top-0 bg-transparent">
                            <div class="text-center"><a class="btn btn-outline-dark mt-auto" href="{% url 'Tienda:AddCart' product.id %}" onclick="addCart(1)" >Add to Cart</a></div>
                        </div>
                    </div>
                </div>

                {% endfor %}

                <!---->

            </div>
        </div>
    </section>

<script>
    window.onload = function () {
      setCart({{ lenCart }})
    }
  </script>


{% endblock content %}

templates/new_category.html
{% extends 'base.html' %}
{% load l10n %}
{% block title %}Shop - New Category{% endblock title %}

{% block content %}

{% if "valid" in request.GET %}
<p>Successfully created</p>

{% endif %}

{% if "error" in request.GET %}
<p>An error occurred</p>

{% endif %}


<form action="" method="POST">{% csrf_token %}
    <table>
        <tr><th><label for="name">Name: </label></th><td><input type="text" name="name" id="name" required></td></tr>
        <tr><th><input type="submit" value="Create"></th></tr>
    </table>

</form>
{% endblock content %}

templates/new_product.html
{% extends 'base.html' %}
{% load l10n %}
{% block title %}Shop - New Product{% endblock title %}

{% block content %}

<form action="" method="POST" enctype="multipart/form-data"> {% csrf_token %}

    <table>
    <tr><th><label for="code">Code: </label></th><td><input type="text" name="code" id="code" required></td></tr>
    <tr><th><label for="title">Title: </label></th><td><input type="text" name="title" id="title"></td></tr>
 
    <tr><th><label for="description">Description: </label></th><td><textarea name="description" id="description" cols="30" rows="10"></textarea></td></tr>
 
    <tr><th><label for="category">Category: </label></th><td>
 
      <!-- <select name="category" id="category"> -->
 
       {% for category in categories %}
     
      <!-- <option value="{{ category.name }}">{{ category.name }}</option>        agregar {} ->  % url 'datos:editar' prueba.id %        -->

      <input type="checkbox" id="{{ category.name }}" name="checkbox" value="{{ category.name }}">
      <label for="{{ category.name }}"> {{ category.name }}</label><br>

       {% endfor %}
 
       </select></td></tr>
    
     <tr><th><label for="image">Image: </label></th><td> <input type="file" id="image" name="image" accept="image/png, image/jpeg">  </td></tr>
 
       <tr><th><label for="price">Price: </label></th><td><input type="text" name="price" id="price"> </td></tr>
 
     <tr><th><input type="submit" value="Save"></th></tr>
     </table>
 
 
  </form>




{% endblock content %}